In [2]:
with open('data/bleak.txt', 'rt') as f:
    bleak = f.read()
    
import nltk
words = nltk.word_tokenize(bleak)

In [31]:
words = [word.lower() for word in words]

429006


In [33]:
vocab = set(words)
print(len(words))
print(len(vocab))

429006
16145


In [34]:
with open('data/glove/glove.6B.50d.txt', 'rt') as f:
    glove = f.readlines()
print(len(glove))

400000


In [19]:
import numpy as np

In [155]:
small_glove = {}
all_embeddings = []
full_vocab = []
for line in glove:
    word = line.split()[0].lower()
    embedding = np.array(line.split()[1:], dtype=np.float64)
#     if word in vocab:
    small_glove[word] = {'vector': embedding}
    all_embeddings.append(embedding)
    full_vocab.append(word)

In [141]:
len(small_glove.keys())

400000

In [142]:
vocab - small_glove.keys()

{'stair-head',
 'volumnia',
 'presentime',
 'by-street',
 'echoings',
 'card-table',
 'mlud',
 'haughtinesses',
 'adjuring',
 'between-whiles',
 'big-wigs',
 'housetops',
 'public-houses',
 'bank-notes',
 'driblets',
 'idlest',
 'tea-trays',
 'delusive',
 "conjuror's",
 'boythorn',
 'unscrews',
 'nomadically',
 'hanger-on',
 "'spend",
 'hurly-burly',
 "t'others",
 'coodle',
 'trimly',
 'window-pane',
 'harum-scarum',
 'pocket-book',
 'death-like',
 'lodge-gate',
 'tax-gathering',
 'half-dozenth',
 'worst-looking',
 "you're",
 'self-reproaches',
 'water-butt',
 'clear-starched',
 'churchyard-step',
 'drum-head',
 'swept-out',
 'epicure-like',
 'askant',
 'smelling-bottle',
 'cap-border',
 'reticule',
 'cheeseming',
 'oyster-knife',
 'loodle',
 'black-beetle',
 'reconsigning',
 'ticket-porters',
 'lattice-windows',
 "mother's",
 'speechlessly',
 'reconsignment',
 'neckcloths',
 'slow-retreating',
 'writing-room',
 'feariocious',
 "kenge's",
 "everybody's",
 'dish-covers',
 "p'raps",
 'go

In [143]:
small_glove['dog']

{'vector': array([ 0.11008  , -0.38781  , -0.57615  , -0.27714  ,  0.70521  ,
         0.53994  , -1.0786   , -0.40146  ,  1.1504   , -0.5678   ,
         0.0038977,  0.52878  ,  0.64561  ,  0.47262  ,  0.48549  ,
        -0.18407  ,  0.1801   ,  0.91397  , -1.1979   , -0.5778   ,
        -0.37985  ,  0.33606  ,  0.772    ,  0.75555  ,  0.45506  ,
        -1.7671   , -1.0503   ,  0.42566  ,  0.41893  , -0.68327  ,
         1.5673   ,  0.27685  , -0.61708  ,  0.64638  , -0.076996 ,
         0.37118  ,  0.1308   , -0.45137  ,  0.25398  , -0.74392  ,
        -0.086199 ,  0.24068  , -0.64819  ,  0.83549  ,  1.2502   ,
        -0.51379  ,  0.04224  , -0.88118  ,  0.7158   ,  0.38519  ])}

In [144]:
embs = np.array(all_embeddings)

In [145]:
maxes = np.max(embs, axis = 0)
mins = np.min(embs, axis = 0)

In [175]:
hyperplanes = []
for a in range(5):
    hyperplane = []
    for a, b in zip(mins, maxes):
        hyperplane.append(np.random.uniform(a, b))
    hyperplanes.append(np.array(hyperplane))
hyperplanes

[array([-3.2935355 , -2.34170844, -2.86891695,  0.24053055,  4.20593108,
         3.09386037, -3.14267772,  2.75236011, -0.2914657 ,  2.75322769,
        -1.00236723, -1.52792125,  0.87521757,  3.38390317, -3.8223763 ,
        -2.52794989,  3.88417268,  0.70571952,  1.30365207,  0.27781862,
         1.28474395,  1.13359773, -4.82142328,  1.74206007, -0.04161723,
        -0.671093  , -2.75241279,  0.58371422,  2.70575495, -0.88222377,
         1.6760261 , -0.25001539,  4.12683081,  0.93836281,  0.64331889,
         1.67553277,  2.10680506, -4.11607938, -4.07322616,  0.62271119,
         1.28004466,  3.34929112, -0.3697607 , -1.70872199,  1.40676941,
        -0.56798262,  1.47628007, -0.92843587, -2.51507504, -0.06301802]),
 array([-2.24315619e-01, -7.98280669e-01,  1.30139677e+00,  5.22941061e+00,
         6.73546339e-04,  8.48139105e-01,  3.01563696e+00, -1.19723285e+00,
         2.85302333e+00,  1.20560305e+00, -1.76181939e-01, -1.17049124e+00,
        -8.31767183e-01,  2.96566975e+00

In [176]:
small_glove.get('pigss', {'vector': 0})['vector']

0

In [185]:
# words = ['the', 'pig', 'dog', 'cat', 'fox', 'wolf']
buckets = {}
for word in full_vocab:

    keys = []
    for hyperplane in hyperplanes:
#         products = hyperplane*small_glove.get(word, {'vector': 0})['vector']
#         hashcount = 0
#         for i, product in enumerate(products):
#             if product>=0:
#                 hashcount+= (2**1)*1
        keys.append(np.sign(np.sum(hyperplane*small_glove.get(word, {'vector': 0})['vector'])))
    key = (tuple(keys))
    if key not in buckets.keys():
        buckets[key] = [word]
    else:
        buckets[key].append(word)
    if word in small_glove.keys():
        small_glove[word]['key'] = key
buckets

{(1.0, -1.0, -1.0, -1.0, -1.0): ['the',
  ',',
  'a',
  '"',
  "'s",
  'for',
  'that',
  'on',
  'was',
  'with',
  'as',
  'it',
  'by',
  "''",
  '``',
  'an',
  'but',
  'this',
  'which',
  'their',
  'its',
  'one',
  'also',
  "'",
  'first',
  'up',
  'out',
  "n't",
  'over',
  'into',
  'you',
  'world',
  'three',
  'against',
  'while',
  'made',
  'just',
  'day',
  'second',
  'group',
  'any',
  'through',
  'four',
  'being',
  'down',
  'back',
  'off',
  'south',
  'well',
  'make',
  'work',
  'home',
  'get',
  'another',
  'five',
  'called',
  '?',
  'very',
  'my',
  'north',
  'public',
  'early',
  'court',
  'says',
  'left',
  'good',
  'going',
  'number',
  'known',
  'six',
  'members',
  'each',
  'place',
  'go',
  'third',
  'right',
  'local',
  'best',
  'own',
  'came',
  "'re",
  'help',
  'series',
  'play',
  'me',
  'without',
  'history',
  'began',
  'name',
  'film',
  'led',
  'central',
  'air',
  'come',
  'little',
  'put',
  'past',
  'ha

In [186]:
for key, value in buckets.items():
    print(key, len(value))

(1.0, -1.0, -1.0, -1.0, -1.0) 2709
(-1.0, -1.0, -1.0, -1.0, -1.0) 3309
(1.0, -1.0, -1.0, -1.0, 1.0) 3865
(1.0, 1.0, -1.0, 1.0, -1.0) 20603
(-1.0, -1.0, -1.0, -1.0, 1.0) 4296
(1.0, -1.0, -1.0, 1.0, -1.0) 5825
(-1.0, 1.0, -1.0, -1.0, 1.0) 6858
(-1.0, -1.0, 1.0, -1.0, -1.0) 8264
(-1.0, -1.0, -1.0, 1.0, -1.0) 4525
(1.0, -1.0, -1.0, 1.0, 1.0) 2955
(1.0, 1.0, -1.0, -1.0, -1.0) 6882
(-1.0, -1.0, -1.0, 1.0, 1.0) 2484
(1.0, 1.0, -1.0, -1.0, 1.0) 7646
(-1.0, 1.0, -1.0, -1.0, -1.0) 6834
(1.0, -1.0, 1.0, 1.0, 1.0) 11004
(-1.0, 1.0, -1.0, 1.0, -1.0) 11530
(-1.0, -1.0, 1.0, 1.0, -1.0) 19282
(1.0, -1.0, 1.0, -1.0, -1.0) 4493
(1.0, -1.0, 1.0, -1.0, 1.0) 7511
(-1.0, -1.0, 1.0, -1.0, 1.0) 12341
(1.0, 1.0, -1.0, 1.0, 1.0) 8643
(1.0, -1.0, 1.0, 1.0, -1.0) 17763
(-1.0, -1.0, 1.0, 1.0, 1.0) 10421
(-1.0, 1.0, 1.0, -1.0, 1.0) 22480
(-1.0, 1.0, -1.0, 1.0, 1.0) 4728
(1.0, 1.0, 1.0, -1.0, -1.0) 14178
(-1.0, 1.0, 1.0, -1.0, -1.0) 16913
(1.0, 1.0, 1.0, 1.0, -1.0) 54416
(-1.0, 1.0, 1.0, 1.0, 1.0) 17200
(1.0, 1.0, 1

In [187]:
sorted(buckets.keys())

[(-1.0, -1.0, -1.0, -1.0, -1.0),
 (-1.0, -1.0, -1.0, -1.0, 1.0),
 (-1.0, -1.0, -1.0, 1.0, -1.0),
 (-1.0, -1.0, -1.0, 1.0, 1.0),
 (-1.0, -1.0, 1.0, -1.0, -1.0),
 (-1.0, -1.0, 1.0, -1.0, 1.0),
 (-1.0, -1.0, 1.0, 1.0, -1.0),
 (-1.0, -1.0, 1.0, 1.0, 1.0),
 (-1.0, 1.0, -1.0, -1.0, -1.0),
 (-1.0, 1.0, -1.0, -1.0, 1.0),
 (-1.0, 1.0, -1.0, 1.0, -1.0),
 (-1.0, 1.0, -1.0, 1.0, 1.0),
 (-1.0, 1.0, 1.0, -1.0, -1.0),
 (-1.0, 1.0, 1.0, -1.0, 1.0),
 (-1.0, 1.0, 1.0, 1.0, -1.0),
 (-1.0, 1.0, 1.0, 1.0, 1.0),
 (1.0, -1.0, -1.0, -1.0, -1.0),
 (1.0, -1.0, -1.0, -1.0, 1.0),
 (1.0, -1.0, -1.0, 1.0, -1.0),
 (1.0, -1.0, -1.0, 1.0, 1.0),
 (1.0, -1.0, 1.0, -1.0, -1.0),
 (1.0, -1.0, 1.0, -1.0, 1.0),
 (1.0, -1.0, 1.0, 1.0, -1.0),
 (1.0, -1.0, 1.0, 1.0, 1.0),
 (1.0, 1.0, -1.0, -1.0, -1.0),
 (1.0, 1.0, -1.0, -1.0, 1.0),
 (1.0, 1.0, -1.0, 1.0, -1.0),
 (1.0, 1.0, -1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0, -1.0, -1.0),
 (1.0, 1.0, 1.0, -1.0, 1.0),
 (1.0, 1.0, 1.0, 1.0, -1.0),
 (1.0, 1.0, 1.0, 1.0, 1.0)]

In [188]:
from sklearn.metrics.pairwise import cosine_similarity

target_word_vector = small_glove['pig']['vector']

candidates = []
for candidate in buckets[small_glove['pig']['key']]:
    candidates.append((cosine_similarity(small_glove[candidate]['vector'].reshape(1,-1), target_word_vector.reshape(1,-1)), candidate))    

In [189]:
from operator import itemgetter
sorted(candidates, key = itemgetter(0), reverse=True)

[(array([[1.]]), 'pig'),
 (array([[0.78663537]]), 'goat'),
 (array([[0.72044307]]), 'bite'),
 (array([[0.68867154]]), 'bird'),
 (array([[0.67767648]]), 'snake'),
 (array([[0.67654192]]), 'goose'),
 (array([[0.6473941]]), 'bites'),
 (array([[0.64311835]]), 'egg'),
 (array([[0.63906932]]), 'ox'),
 (array([[0.63873779]]), 'shark'),
 (array([[0.63673507]]), 'bulaga'),
 (array([[0.6276484]]), 'crab'),
 (array([[0.60680021]]), 'rooster'),
 (array([[0.59237398]]), 'wild'),
 (array([[0.58624509]]), 'feral'),
 (array([[0.58080008]]), 'slaughter'),
 (array([[0.57599577]]), 'monster'),
 (array([[0.56858114]]), 'lobster'),
 (array([[0.56653411]]), 'sucker'),
 (array([[0.56377001]]), 'moose'),
 (array([[0.56057359]]), 'habit'),
 (array([[0.55911102]]), 'belly'),
 (array([[0.54652328]]), 'peanuts'),
 (array([[0.54436446]]), 'octopus'),
 (array([[0.54157781]]), 'pickled'),
 (array([[0.54138104]]), 'fruit'),
 (array([[0.5396934]]), 'swill'),
 (array([[0.53430101]]), 'packs'),
 (array([[0.53061546]]), 

In [139]:
all_embeddings[0]

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01])

In [163]:
target_word_vector = small_glove['pig']['vector']

candidates = []
counter = 0
for candidate in full_vocab:
    if not counter %1000:
        print(counter)
    counter+=1
    candidates.append((cosine_similarity(small_glove[candidate]['vector'].reshape(1,-1), target_word_vector.reshape(1,-1)), candidate))    

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000


In [154]:
len(vocab)

16145

In [164]:
sorted(candidates, key = itemgetter(0), reverse=True)

[(array([[1.]]), 'pig'),
 (array([[0.83343508]]), 'pigs'),
 (array([[0.82909772]]), 'cow'),
 (array([[0.81607023]]), 'rabbit'),
 (array([[0.78903346]]), 'sheep'),
 (array([[0.78663537]]), 'goat'),
 (array([[0.76070636]]), 'meat'),
 (array([[0.75755582]]), 'elephant'),
 (array([[0.75752738]]), 'cows'),
 (array([[0.74900616]]), 'dog'),
 (array([[0.74739972]]), 'chickens'),
 (array([[0.74455852]]), 'cat'),
 (array([[0.74119012]]), 'hog'),
 (array([[0.7395955]]), 'duck'),
 (array([[0.73599678]]), 'animal'),
 (array([[0.73210586]]), 'rat'),
 (array([[0.73163116]]), 'monkey'),
 (array([[0.72159528]]), 'peppa'),
 (array([[0.72128537]]), 'chicken'),
 (array([[0.72044307]]), 'bite'),
 (array([[0.7114471]]), 'intestines'),
 (array([[0.69847176]]), 'cattle'),
 (array([[0.69723514]]), 'mad'),
 (array([[0.69484632]]), 'pet'),
 (array([[0.69432593]]), 'puppy'),
 (array([[0.69298522]]), 'boar'),
 (array([[0.69252918]]), 'cloned'),
 (array([[0.69022905]]), 'rats'),
 (array([[0.68867154]]), 'bird'),
 (