In [11]:
import nltk
import numpy as np

from tqdm.notebook import tqdm, trange
import time

with open('data/bleak.txt', 'rt') as f:
    bleak = f.read()
    
words = nltk.word_tokenize(bleak)
words = [word.lower() for word in words]

In [6]:
with open('tokenized_text.txt', 'wt') as f:
    f.write(' '.join(words))

In [7]:
vocab = set(words)
print(len(words))
print(len(vocab))

429006
16145


In [9]:
glove_400k = 'data/glove/glove.6B.50d.txt'
glove_1_9MM = 'data/glove/glove.42B.300d.txt'
with open(glove_1_9MM, 'rt') as f:
    glove = f.readlines()
print(len(glove))

1917494


In [12]:
small_glove = {}
all_embeddings = []
full_vocab = []

counter = 0
for line in tqdm(glove):
    if not counter%10000:
        print(counter)
    counter+=1
    word = line.split()[0].lower()
    embedding = np.array(line.split()[1:], dtype=np.float64)
    small_glove[word] = {'vector': embedding}
    all_embeddings.append(embedding)
    full_vocab.append(word)
len(small_glove.keys())
# vocab - small_glove.keys()

  0%|          | 0/1917494 [00:00<?, ?it/s]

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
13

1917494

In [212]:
small_glove['dog']

{'vector': array([-3.3575e-01,  3.8897e-01, -4.1929e-01, -3.3219e-01,  5.3170e-01,
        -2.5839e-01, -2.3869e+00, -4.3443e-01, -3.9760e-01, -9.9356e-01,
         4.7093e-01, -1.6265e-01, -1.3474e-01, -1.3060e+00,  3.4694e-01,
         1.2150e-01, -1.5811e-01, -1.1231e-02, -4.6560e-01, -1.8031e-01,
         2.6682e-02, -2.8445e-02, -4.4228e-01,  2.0955e-01,  4.4307e-02,
         2.7514e-01, -2.3140e-01, -1.0864e-01, -8.7113e-03,  2.0522e-01,
         3.6109e-01, -3.5431e-01,  2.5217e-01,  2.6608e-01,  1.1942e-01,
        -2.1606e-01,  7.3164e-02,  2.5023e-01,  2.4612e-01,  2.0797e-01,
        -1.8702e-01, -3.8054e-02,  2.3604e-01,  4.2484e-01,  1.0187e-01,
         5.8443e-02, -6.0782e-01, -5.2279e-01, -2.6276e-02, -1.4402e-01,
         2.2169e-01, -1.5850e-01, -8.1178e-01,  8.2893e-02, -2.2136e-02,
        -1.2966e-01,  1.7201e-01,  6.2484e-01, -2.3122e-02, -1.5704e-01,
        -4.1946e-01, -4.9499e-01,  5.6224e-02, -8.1352e-02,  3.5428e-01,
         1.5145e-01, -2.6535e-01,  1.0071

In [13]:
embs = np.array(all_embeddings)
maxes = np.max(embs, axis = 0)
mins = np.min(embs, axis = 0)

In [14]:
hyperplanes = []
for a in trange(7):
    hyperplane = []
    for a, b in zip(mins, maxes):
        hyperplane.append(np.random.uniform(a, b))
    hyperplanes.append(np.array(hyperplane))

  0%|          | 0/7 [00:00<?, ?it/s]

In [15]:
buckets = {}
for word in tqdm(full_vocab):
    keys = []
    for hyperplane in hyperplanes:
        keys.append(np.sign(np.sum(hyperplane*small_glove.get(word, {'vector': 0})['vector'])))
    key = (tuple(keys))
    if key not in buckets.keys():
        buckets[key] = [word]
    else:
        buckets[key].append(word)
    if word in small_glove.keys():
        small_glove[word]['key'] = key
buckets

  0%|          | 0/1917494 [00:00<?, ?it/s]

{(1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0): [',',
  'to',
  'of',
  'a',
  'in',
  '"',
  'is',
  ':',
  ')',
  'that',
  'you',
  'it',
  'on',
  '-',
  'with',
  'this',
  'at',
  'as',
  'be',
  'from',
  'or',
  'your',
  '!',
  '?',
  'all',
  'will',
  'an',
  'can',
  'they',
  "n't",
  'do',
  'if',
  'one',
  'has',
  'so',
  'about',
  'what',
  'there',
  'up',
  'out',
  ';',
  'their',
  'our',
  "'",
  'which',
  'no',
  'would',
  '1',
  'some',
  '[',
  ']',
  'also',
  'other',
  'how',
  'may',
  '2',
  'them',
  'people',
  'any',
  'now',
  'than',
  'good',
  'into',
  'here',
  'make',
  '3',
  'very',
  'over',
  'most',
  'know',
  'well',
  'use',
  'two',
  'did',
  'could',
  'day',
  'great',
  'free',
  'many',
  'way',
  'work',
  'because',
  'should',
  'even',
  'years',
  'much',
  'does',
  'where',
  '4',
  'go',
  'need',
  'last',
  '2012',
  '=',
  'really',
  'information',
  'want',
  '5',
  'take',
  'such',
  'those',
  '2011',
  'before',
  'being

In [229]:
for key, value in buckets.items():
    print(key, len(value))

(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0) 5648
(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0) 8898
(1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0) 3361
(1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0) 5007
(1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0) 4577
(1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0) 3747
(1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0) 4558
(1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0) 4037
(1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0) 3161
(-1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0) 7672
(1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0) 3732
(-1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0) 3529
(1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0) 2898
(-1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0) 5182
(1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0) 2548
(1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0) 4003
(1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0) 4623
(1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0) 4408
(1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0) 4090
(1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0) 2678
(1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0) 8157
(-1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0) 3833
(-1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0) 4634
(1.0, 1.0, 

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

target_word = 'truculent'
target_word_vector = small_glove[target_word]['vector']

candidates = []
for candidate in tqdm(buckets[small_glove[target_word]['key']]):
    candidates.append((cosine_similarity(small_glove[candidate]['vector'].reshape(1,-1), target_word_vector.reshape(1,-1)), candidate))    

  0%|          | 0/6737 [00:00<?, ?it/s]

In [17]:
from operator import itemgetter
sorted(candidates, key = itemgetter(0), reverse=True)

[(array([[1.]]), 'truculent'),
 (array([[0.50277231]]), 'querulous'),
 (array([[0.49788201]]), 'diffident'),
 (array([[0.48742657]]), 'ill-tempered'),
 (array([[0.47380077]]), 'cantankerous'),
 (array([[0.47094026]]), 'vituperative'),
 (array([[0.44266095]]), 'crotchety'),
 (array([[0.43418304]]), 'lackadaisical'),
 (array([[0.40281669]]), 'bad-tempered'),
 (array([[0.39348826]]), 'pusillanimous'),
 (array([[0.39282506]]), 'demagogic'),
 (array([[0.38770594]]), 'mopey'),
 (array([[0.38760467]]), 'unenthusiastic'),
 (array([[0.38670132]]), 'inarticulate'),
 (array([[0.36869263]]), 'gruffness'),
 (array([[0.3676274]]), 'scowl'),
 (array([[0.3674901]]), 'bilious'),
 (array([[0.36249345]]), 'stodgy'),
 (array([[0.35060034]]), 'luddite'),
 (array([[0.34891567]]), 'worryingly'),
 (array([[0.34850256]]), 'splenetic'),
 (array([[0.3379835]]), 'rumpled'),
 (array([[0.33650785]]), 'begrudging'),
 (array([[0.33563994]]), 'one-eyed'),
 (array([[0.33163512]]), 'encouragingly'),
 (array([[0.32525325

In [208]:
# target_word_vector = small_glove['pig']['vector']

# candidates = []
# counter = 0
# for candidate in full_vocab:
#     if not counter %1000:
#         print(counter)
#     counter+=1
#     candidates.append((cosine_similarity(small_glove[candidate]['vector'].reshape(1,-1), target_word_vector.reshape(1,-1)), candidate))    

In [19]:
vocab - set(full_vocab)

{'storing-up',
 'coach-window',
 'moiler',
 'a-doing',
 'state-bed',
 'follerer',
 'gen-teel',
 'public-looking',
 'court-yards',
 "d'rectly",
 'swallering',
 'boguey',
 'staringly',
 'jarnders',
 'imeantersay',
 'smallweeds',
 'cobweb-covered',
 "anybody's",
 'plantation-fence',
 'law-writer',
 "'your",
 'whist-player',
 'bayonet-charge',
 "heaven's",
 'uncompanionable',
 'racket-courts',
 'wiolincellers',
 'sorrowful-looking',
 'lady-birds',
 "hist'ry",
 "'to",
 'skumpling',
 'forrenner',
 'terrace-pavement',
 'ink-splashed',
 "'manor",
 'hat-boxes',
 'engrosser',
 "'ca",
 'tapn',
 "'who",
 'shopofwomen',
 'noun-substantive',
 'garden-earth',
 'readjourned',
 'affectionately.',
 'soldier-looking',
 'remindingmanfact',
 'potboy',
 'unharnessing',
 'reconcilements',
 'a-being',
 'foot-passengers',
 'hoop-stick',
 'law-stationering',
 'dog-hutch',
 'direfully',
 'a-wisitin',
 'sticking-plaster',
 'petty-bags',
 'pardiggles',
 'parlour-door',
 'trodden-down',
 'wepping',
 'de-vil',
 "the

# Train our own embedding vectors to capture the older words from our novel which are missed in Glove

In [20]:
glove_dickens = 'glove/vectors.txt'
with open(glove_dickens, 'rt') as f:
    glove = f.readlines()
print(len(glove))

4545


In [26]:
my_embeddings = set([word.split()[0] for word in glove])

In [35]:
list(words_missing_from_glove)[:20]

['storing-up',
 'coach-window',
 'moiler',
 'a-doing',
 'state-bed',
 'follerer',
 'gen-teel',
 'public-looking',
 'court-yards',
 "d'rectly",
 'swallering',
 'boguey',
 'staringly',
 'jarnders',
 'imeantersay',
 'smallweeds',
 'cobweb-covered',
 "anybody's",
 'plantation-fence',
 'law-writer']

In [34]:
list(my_embeddings.intersection(words_missing_from_glove))[:20]

['dedlocks',
 'borrioboolan',
 'ap-kerrig',
 "'ouse",
 "'my",
 'bogsby',
 'sangsby',
 "guppy's",
 'chadbands',
 'tom-all-alone',
 'squod',
 'swosser',
 "'now",
 'inkwhich',
 'turveydrop',
 'law-writer',
 'grubble',
 'a-moving',
 'gownd',
 "'you"]

# Next steps - use nltk.synset.definition() to show definitions of words.
# Wider range of novels to train missing embeddings
# Visualise embeddings with tensorflow embedding visualiser